### PR TITLE
Make front more obvious

### PR DESCRIPTION
**Pull request by pezholio**
Remove the rear carriage, so it's clearer which way the train's facing:

download 3

### CODE REVIEW

**Comment by Floppy** [comment]
choo choo

**Comment by Floppy** [comment]
does the front always point south? CSS can do that right? :)

**Comment by Floppy** [comment]
```
div {
   float: south;
}
```

**Comment by Floppy** [comment]
:trollface:

**Comment by pezholio** [comment]
Lulz

**Pull request merged**
